# Generated by Django 5.2.8 on 2025-11-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'asset_classes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('timezone', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exchanges',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('isin', models.CharField(blank=True, db_index=True, max_length=12)),
                ('lot_size', models.IntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default=0.05, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.assetclass')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.currency')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.exchange')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('trades', models.IntegerField(null=True)),
                ('timeframe', models.CharField(default='1D', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='data.asset')),
            ],
            options={
                'db_table': 'bars',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='bars_asset_i_af164f_idx'), models.Index(fields=['timestamp'], name='bars_timesta_ddaa14_idx')],
                'unique_together': {('asset', 'timestamp', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('split', 'Split'), ('dividend', 'Dividend'), ('bonus', 'Bonus'), ('rights', 'Rights'), ('merger', 'Merger')], max_length=20)),
                ('ex_date', models.DateField(db_index=True)),
                ('record_date', models.DateField(null=True)),
                ('payment_date', models.DateField(null=True)),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('details', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='data.asset')),
            ],
            options={
                'db_table': 'corporate_actions',
                'ordering': ['-ex_date'],
                'indexes': [models.Index(fields=['asset', 'ex_date'], name='corporate_a_asset_i_e52620_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['symbol', 'exchange'], name='assets_symbol_5efd73_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['exchange', 'asset_class'], name='assets_exchang_6c2cbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('symbol', 'exchange')},
        ),
    ]
