# Generated by Django 5.2.8 on 2025-11-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_return', models.DecimalField(decimal_places=4, max_digits=10)),
                ('annual_return', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('sortino_ratio', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(decimal_places=4, max_digits=10)),
                ('max_drawdown_duration_days', models.IntegerField(null=True)),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('total_trades', models.IntegerField()),
                ('winning_trades', models.IntegerField()),
                ('losing_trades', models.IntegerField()),
                ('avg_win', models.DecimalField(decimal_places=4, max_digits=20)),
                ('avg_loss', models.DecimalField(decimal_places=4, max_digits=20)),
                ('avg_trade_duration_minutes', models.FloatField(null=True)),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_slippage', models.DecimalField(decimal_places=4, max_digits=20)),
                ('implementation_shortfall_bps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('strategy_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_metrics', to='strategies.strategyrun')),
            ],
            options={
                'db_table': 'backtest_metrics',
            },
        ),
        migrations.CreateModel(
            name='EquityCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('equity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cash', models.DecimalField(decimal_places=4, max_digits=20)),
                ('positions_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('daily_return', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('drawdown', models.DecimalField(decimal_places=4, max_digits=10)),
                ('strategy_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_curve', to='strategies.strategyrun')),
            ],
            options={
                'db_table': 'equity_curves',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['strategy_run', 'timestamp'], name='equity_curv_strateg_bb7d9b_idx')],
                'unique_together': {('strategy_run', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekly_return', models.DecimalField(decimal_places=4, max_digits=10)),
                ('gross_return', models.DecimalField(decimal_places=4, max_digits=10)),
                ('net_return', models.DecimalField(decimal_places=4, max_digits=10)),
                ('trades_count', models.IntegerField(default=0)),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('slippage', models.DecimalField(decimal_places=4, max_digits=20)),
                ('strategy_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_returns', to='strategies.strategyrun')),
            ],
            options={
                'db_table': 'weekly_returns',
                'ordering': ['year', 'week'],
                'indexes': [models.Index(fields=['strategy_run', 'year', 'week'], name='weekly_retu_strateg_3e468e_idx')],
                'unique_together': {('strategy_run', 'year', 'week')},
            },
        ),
    ]
