# Generated by Django 5.2.8 on 2025-11-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop_loss', 'Stop Loss'), ('stop_loss_market', 'Stop Loss Market')], max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('filled_quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('trigger_price', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('avg_fill_price', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('partial', 'Partial'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('broker_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('filled_at', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.asset')),
                ('strategy_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='strategies.strategyrun')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('exchange_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('stt', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('gst', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('broker_execution_id', models.CharField(blank=True, max_length=100)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='live.order')),
            ],
            options={
                'db_table': 'executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('avg_entry_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=4, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.asset')),
                ('strategy_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='strategies.strategyrun')),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('equity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cash', models.DecimalField(decimal_places=4, max_digits=20)),
                ('positions_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=4, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_orders', models.IntegerField(default=0)),
                ('filled_orders', models.IntegerField(default=0)),
                ('rejected_orders', models.IntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(null=True)),
                ('max_latency_ms', models.FloatField(null=True)),
                ('strategy_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_metrics', to='strategies.strategyrun')),
            ],
            options={
                'db_table': 'session_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('entry_commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('exit_commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('slippage', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pnl', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pnl_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('duration_minutes', models.IntegerField()),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.asset')),
                ('entry_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_trades', to='live.order')),
                ('exit_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_trades', to='live.order')),
                ('strategy_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='strategies.strategyrun')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-exited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['strategy_run', 'status'], name='orders_strateg_bda125_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['asset', 'created_at'], name='orders_asset_i_59581c_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['strategy_run', 'asset'], name='positions_strateg_21f028_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('strategy_run', 'asset')},
        ),
        migrations.AddIndex(
            model_name='sessionmetrics',
            index=models.Index(fields=['strategy_run', '-timestamp'], name='session_met_strateg_d0b830_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['strategy_run', 'exited_at'], name='trades_strateg_eebaff_idx'),
        ),
    ]
